// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DockerTest.UI.Database;

namespace DockerTest.UI.Migrations
{
    [DbContext(typeof(PersonsContext))]
    [Migration("20181118135213_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleApp.Database.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new { Id = 1, Address = "Belarus, Gomel", Age = 21, Name = "Aliaksei Harshkalep1" },
                        new { Id = 2, Address = "Belarus, Gomel", Age = 22, Name = "Aliaksei Harshkalep2" },
                        new { Id = 3, Address = "Belarus, Gomel", Age = 23, Name = "Aliaksei Harshkalep3" },
                        new { Id = 4, Address = "Belarus, Gomel", Age = 24, Name = "Aliaksei Harshkalep4" },
                        new { Id = 5, Address = "Belarus, Gomel", Age = 25, Name = "Aliaksei Harshkalep5" },
                        new { Id = 6, Address = "Belarus, Gomel", Age = 26, Name = "Aliaksei Harshkalep6" },
                        new { Id = 7, Address = "Belarus, Gomel", Age = 27, Name = "Aliaksei Harshkalep7" },
                        new { Id = 8, Address = "Belarus, Gomel", Age = 28, Name = "Aliaksei Harshkalep8" },
                        new { Id = 9, Address = "Belarus, Gomel", Age = 29, Name = "Aliaksei Harshkalep9" },
                        new { Id = 10, Address = "Belarus, Gomel", Age = 30, Name = "Aliaksei Harshkalep10" },
                        new { Id = 11, Address = "Belarus, Gomel", Age = 31, Name = "Aliaksei Harshkalep11" },
                        new { Id = 12, Address = "Belarus, Gomel", Age = 32, Name = "Aliaksei Harshkalep12" },
                        new { Id = 13, Address = "Belarus, Gomel", Age = 33, Name = "Aliaksei Harshkalep13" },
                        new { Id = 14, Address = "Belarus, Gomel", Age = 34, Name = "Aliaksei Harshkalep14" },
                        new { Id = 15, Address = "Belarus, Gomel", Age = 35, Name = "Aliaksei Harshkalep15" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
